export const dataSourcesInfo = {
  dsr_environments: {
    tableId: 'dsr_environment',
    dataSourceType: 'Dataverse',
    apis: {},
  },
  dsr_storagesnapshots: {
    tableId: 'dsr_storagesnapshot',
    dataSourceType: 'Dataverse',
    apis: {},
  },
  dsr_settings: {
    tableId: 'dsr_setting',
    dataSourceType: 'Dataverse',
    apis: {},
  },
  // On-demand per-table storage flow. Auto-generated by `power-apps add-flow`
  // into power-platform/code-app/.power/schemas/appschemas/dataSourcesInfo.ts;
  // mirrored here so both Dataverse and Connector data sources share one client.
  getdataversetablestorage: {
    tableId: '',
    version: '',
    primaryKey: '',
    dataSourceType: 'Connector',
    apis: {
      Run: {
        path: '/{connectionId}/triggers/manual/run',
        method: 'POST',
        parameters: [
          { name: 'connectionId', in: 'path', required: true, type: 'string' },
          { name: 'input', in: 'body', required: true, type: 'object' },
          { name: 'api-version', in: 'query', required: true, type: 'string' },
        ],
        responseInfo: {
          '200': { type: 'object' },
          default: { type: 'object' },
        },
      },
    },
  },
}
